name: Build and Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: "Release"

jobs:
  build:
    strategy:
      matrix:
      fail-fast: false
      matrix:
        os: [
          "ubuntu-latest",
          "macOS-latest",
          "windows-latest"
        ]
        python-version: [
          #"3.10", not yet available on ubuntu
          "3.9",
          "3.8",
          "3.7",
          #"3.6" not available anymore on macOS
        ]
        architecture: ["x86", "x64"]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.architecture }} - ${{ matrix.python-version }}
    env:
      DEPENDENCIES: pycryptodome py3rijndael

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade wheel setuptools twine
        pip install pytest ${{ env.DEPENDENCIES }}
    
    # - name: Install module
    #   run: |
    #     pip install . --use-feature=in-tree-build
    
    # - name: Test with pytest
    #   run: |
    #     pytest -v -s

    - name: Build artifact
      run: |
        python setup.py build_ext --inplace

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cppdael-${{ matrix.os }}-${{ env.BUILD_TYPE }}
        path: ${{github.workspace}}/cppdael.cp*-*.*